cfg = {
    "__doc__": "Default configurations",
    "input_size": [417, 417],
    "seed": 1234,
    "cuda_visable": "0,1,2,3",
    "gpu_id": 0,
    "mode": "train",
    "dataset": "VOC",
    "n_steps": 20000,
    "num_workers": 8,
    "label_sets": 0,
    "batch_size": 1,
    "lr_milestones": [10000, 20000, 30000],
    "align_loss_scaler": 1,
    "base_loss_scaler": 0.1,
    "ignore_label": 255,
    "print_interval": 100,
    "save_pred_every": 4000,
    "evaluate_interval": 4000,
    "n_runs": 1,
    "eval": 1,
    "eval_dir": ".",
    "center": 5,
    # "ckpt_dir": "checkpoints/ppnet/2024-11-09-voc-50-fix-w2-s1-lr5e-4-cen5-base0.1-size417-semshare4-F",
    "skip_ways": "v1",
    "output_sem_size": 417,
    "infer_max_iters": 1000,
    "share": 4,
    "pt_lambda": 0.8,
    "un_bs": 3,
    "topk": 30,
    "global_const": 0.8,
    "fix": True,
    "align_loss_cs_scaler": 0,
    "segments": True,
    "p_value_thres": 0.5,
    "resnet": 50,
    "output_dir": ".",
    "model": {"part": True, "semi": False, "sem": True, "resnet": True, "slic": False},
    "task": {"n_ways": 2, "n_shots": 1, "n_queries": 1, "n_unlabels": 1},
    "optim": {"lr": 0.0005, "momentum": 0.9, "weight_decay": 0.0005},
    "slic": {"num_components": 80, "compactness": 80},
    "exp_str": "VOC_part_sem_resnet_w2s1_lr0.0005_cen5_F",
    "path": {
        "log_dir": "./outputs/PANet/",
        "init_path": "./FewShotSeg-dataset/cache/vgg16-397923af.pth",
        "VOC": {
            "data_dir": "./FewShotSeg-dataset/Pascal/VOC2012/",
            "data_split": "trainaug",
        },
    },
    # "resnet_init_path": "checkpoints/ppnet/resnet",
}