#!/bin/bash

#SBATCH -A IscrC_PENELOPE
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_lprod
#SBATCH --time 05:30:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0
#SBATCH --gres=gpu:4
#SBATCH --job-name=validate_model
#SBATCH --out=validate.out
#SBATCH --err=validate.out

srun ./launch_validate_exe $@
