
parameters:
  num_iterations: [5]
  device: [cuda]
  lora_r: [16, 32, 64]
  lr: [0.001, 0.0001]
  target_modules: ["query,value"]
  lora_dropout: [0.1]
  val_num_samples: [1000]
  val_fold_idx: [0, 1, 2, 3]
  model: [label_anything]

other_grids:
