#!/bin/bash

#SBATCH -A IscrC_PENELOPE
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_dbg
#SBATCH --time 00:30:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --job-name=vit_extract
#SBATCH --out=extract.out
#SBATCH --err=extract.out

srun ./slurm/extract_exe_single $@
