#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time 12:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0
#SBATCH --gres=gpu:4
#SBATCH --job-name=test_model
#SBATCH --out=val.out
#SBATCH --err=val.out

srun ./slurm/launch_val_exe $@
