#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --mem=0
#SBATCH --exclusive
#SBATCH --job-name=run
#SBATCH --out=out_pretraining/run_pretraining.log
#SBATCH --err=out_pretraining/run_pretraining.log

srun ./slurm/pretrain_pe_parallel_exe $1